export const areaDictionary = {
    'Emery Computer Science': {
        "vision": ['cvpr', 'iccv', 'eccv'],
        "plan": ['popl', 'pldi', 'oopsla', 'icfp'],
        "soft": ['icse', 'fse', 'ase', 'issta'],
        "ops": ['sosp', 'osdi', 'eurosys', 'fast', 'usenixatc'],
        'metrics': ['imc', 'sigmetrics'],
        'mobile': ['mobisys', 'mobicom', 'sensys'],
        'hpc': ['sc', 'hpdc', 'ics'],
        'bed': ['emsoft', 'rtss', 'rtas'],
        'da': ['iccad', 'dac'],
        'mod': ['vldb', 'sigmod', 'icde', 'pods'],
        'sec': ['ccs', 'oakland', 'usenixsec', 'ndss', 'ieee s&p', 'pets'],
        'comm': ['sigcomm', 'nsdi'],
        'arch': ['asplos', 'isca', 'micro', 'hpca', 'neurlps'],
        'log': ['cav', 'lics'],
        'act': ['focs', 'stoc', 'soda'],
        'mlmining': ['nips', 'icml', 'kdd'],
        'compgraph': ['siggraph', 'siggraph-asia'],
        'ir': ['sigir', 'www'],
        'chi': ['chiconf', 'ubicomp', 'uist', 'imwut, pervasive'],
        'nlp': ['emnlp', 'acl', 'naacl'],
        'robotics': ['icra', 'iros', 'rss'],
        'crypt': ['crypto', 'eurocrypt'],
        'bio': ['ismb', 'recomb'],
        'visual': ['vis', 'vr'],
        'ecom': ['ec', 'wine', 'cse'],
        'ai': ['aaai', 'ijcai']

    },
    'Computer Science': {
        'Artificial Intelligence': ['aaai', 'ijcai'],
        'Computer Vision': ['cvpr', 'eccv', 'iccv'],
        'Machine Learning & Data Mining': ['icml', 'kdd', 'neurips'],
        'Natural Language Processing': ['acl', 'emnlp', 'naacl'],
        'The Web and Information': ['sigir', 'www'],
        'Computer Architecture': ['asplos', 'isca', 'micro', 'hpca'],
        'Computer Networks': ['sigcomm', 'nsdi'],
        'Computer Security': ['ccs', 's&p', 'usenix', 'ndss'],
        'Databases': ['sigmod', 'vldb', 'icde', 'pods'],
        'Design Automation': ['dac', 'iccad'],
        'Embedded and Real-Time Systems': ['emsoft', 'rtas', 'rtss'],
        'High Performance Computing': ['hpdc', 'ics'],
        'Mobile Computing': ['mobicom', 'mobisys', 'sensys'],
        'Measurement and Performance Analysis': ['imc', 'sigmetrics'],
        'Operating Systems': ['osdi', 'sosp', 'eurosys'],
        'Programming Languages': ['pldi', 'popl', 'icfp', 'oopsla'],
        'Software Engineering': ['fse', 'icse', 'issta'],
        'Algorithms & Complexity': ['focs', 'soda', 'stoc', 'crypto', 'eurocrypt'],
        'Logic and Verification': ['cav', 'lics'],
        'Comp. bio & bioinformatics': ['ismb', 'recomb'],
        'Computer Graphics': ['siggraph', 'siggraph asia'],
        'Human-Computer Interaction': ['chi', 'ubicomp', 'uist'],
        'Robotics': ['icra', 'iros', 'rss'],
        'Visualization': ['vis']
    },
    'Physics': {
        'Astronomy and Astrophysics': ['WebSci: Web Science', 'CIDU: Conference on Intelligent Data Understanding', 'IMS: International Microwave Symposium', 'IRMMW-THz: International Conference on Infrared, Millimeter, and Terahertz Waves', 'IRMMW-THz: International Conference on Infrared, Millimeter, and Terahertz Waves', ''],
        'Atomic and Molecular Physics, and Optics': [],
        'Condensed Matter Physics': [],
        'Nuclear and High Energy Physics': [],
        'Surfaces and Interfaces': []
    }
}
//Have to change everything to lowercase