export const areaDictionary = {
    'Emery Computer Science': {
        "vision": ['cvpr', 'iccv', 'eccv'],
        "plan": ['popl', 'pldi', 'oopsla', 'icfp'],
        "soft": ['icse', 'fse', 'ase', 'issta'],
        "ops": ['sosp', 'osdi', 'eurosys', 'fast', 'usenixatc'],
        'metrics': ['imc', 'sigmetrics'],
        'mobile': ['mobisys', 'mobicom', 'sensys'],
        'hpc': ['sc', 'hpdc', 'ics'],
        'bed': ['emsoft', 'rtss', 'rtas'],
        'da': ['iccad', 'dac'],
        'mod': ['vldb', 'sigmod', 'icde', 'pods'],
        'sec': ['ccs', 'oakland', 'usenixsec', 'ndss', 'ieee s&p', 'pets'],
        'comm': ['sigcomm', 'nsdi'],
        'arch': ['asplos', 'isca', 'micro', 'hpca', 'neurlps'],
        'log': ['cav', 'lics'],
        'act': ['focs', 'stoc', 'soda'],
        'mlmining': ['nips', 'icml', 'kdd'],
        'compgraph': ['siggraph', 'siggraph-asia'],
        'ir': ['sigir', 'www'],
        'chi': ['chiconf', 'ubicomp', 'uist', 'imwut, pervasive'],
        'nlp': ['emnlp', 'acl', 'naacl'],
        'robotics': ['icra', 'iros', 'rss'],
        'crypt': ['crypto', 'eurocrypt'],
        'bio': ['ismb', 'recomb'],
        'visual': ['vis', 'vr'],
        'ecom': ['ec', 'wine', 'cse'],
        'ai': ['aaai', 'ijcai']

    },
    'Computer Science': {
        'Artificial Intelligence': ['aaai', 'AAAI Conference on Artificial Intelligence', 'IJCAI', 'International Joint Conference on Artificial Intelligence'],
        'Computer Vision': ['CVPR', 'Computer Vision and Pattern Recognition', 'ECCV', 'European Conference on Computer Vision', 'ICCV', 'International Conference on Computer Vision'],
        'Machine Learning & Data Mining': ['ICML', 'International Conference on Machine Learning', 'KDD', 'Knowledge Discovery and Data Mining', 'NeurIPS', 'Neural Information Processing Systems'],
        'Natural Language Processing': ['ACL', 'Meeting of the Association for Computational Linguistics', 'EMNLP', 'Empirical Methods in Natural Language Processing', 'NAACL', 'North American Chapter of the Association for Computational Linguistics'],
        'The Web and Information': ['SIGIR', 'International ACM SIGIR Conference on Research and Development in Information Retrieval', 'WWW', 'The Web Conference'],
        'Computer Architecture': ['ASPLOS', 'Architectural Support for Programming Languages and Operating Systems', 'ISCA', 'International Symposium on Computer Architecture', 'MICRO', 'International Symposium on Microarchitecture', 'HPCA', 'High-Performance Computer Architecture'],
        'Computer Networks': ['SIGCOMM', 'ACM Special Interest Group on Data Communication', 'NSDI', 'Networked Systems Design and Implementation'],
        'Computer Security': ['CCS', 'Computer and Communications Security', 'S&P', 'IEEE Symposium on Security and Privacy', 'USENIX', 'USENIX Security Symposium', 'NDSS', 'Network and Distributed System Security Symposium'],
        'Databases': ['SIGMOD', 'International Conference on Management of Data', 'VLDB', 'Very Large Data Bases', 'ICDE', 'International Conference on Data Engineering', 'PODS', 'Symposium on Principles of Database Systems'],
        'Design Automation': ['DAC', 'Design Automation Conference', 'ICCAD', 'International Conference on Computer Aided Design'],
        'Embedded and Real-Time Systems': ['EMSOFT', 'Embedded Software', 'RTAS', 'Real Time Technology and Applications Symposium', 'RTSS', 'Real-Time Systems Symposium'],
        'High Performance Computing': ['HPDC', 'High Performance Distributed Computing', 'ICS', 'International Conference on Supercomputing'],
        'Mobile Computing': ['MOBICOM', 'ACM/IEEE International Conference on Mobile Computing and Networking', 'MobiSys', 'International Conference on Mobile Systems, Applications, and Services', 'SenSys', 'International Conference on Embedded Networked Sensor Systems'],
        'Measurement and Performance Analysis': ['IMC', 'Internet Measurement Conference', 'SIGMETRICS', 'Measurement and Modeling of Computer Systems'],
        'Operating Systems': ['OSDI', 'Operating Systems Design and Implementation', 'SOSP', 'Symposium on Operating Systems Principles', 'EuroSys', 'European Conference on Computer Systems'],
        'Programming Languages': ['PLDI', 'Programming Language Design and Implementation', 'POPL', 'Symposium on Principles of Programming Languages', 'ICFP', 'International Conference on Functional Programming', 'OOPSLA', 'Conference on Object-Oriented Programming Systems, Languages, and Applications'],
        'Software Engineering': ['FSE', 'Foundations of Software Engineering', 'ICSE', 'International Conference on Software Engineering', 'ISSTA', 'International Symposium on Software Testing and Analysis'],
        'Algorithms & Complexity': ['FOCS', 'Foundations of Computer Science', 'SODA', 'Symposium on Discrete Algorithms', 'STOC', 'Symposium on the Theory of Computing', 'CRYPTO', 'International Cryptology Conference', 'EUROCRYPT', 'Theory and Application of Cryptographic Techniques'],
        'Logic and Verification': ['CAV', 'Computer Aided Verification', 'LICS', 'Logic in Computer Science'],
        'Comp. bio & bioinformatics': ['ISMB', 'Intelligent Systems in Molecular Biology', 'RECOMB', 'Research in Computational Molecular Biology'],
        'Computer Graphics': ['SIGGRAPH', 'International Conference on Computer Graphics and Interactive Techniques', 'SIGGRAPH Asia', 'SIGGRAPH Conference and Exhibition on Computer Graphics and Interactive Techniques in Asia'],
        'Human-Computer Interaction': ['CHI', 'Human Factors in Computing Systems', 'UbiComp', 'Ubiquitous Computing', 'UIST', 'User Interface Software and Technology'],
        'Robotics': ['ICRA', 'International Conference on Robotics and Automation', 'IROS', 'Intelligent Robots and Systems', 'RSS', 'Robotics, Science and Systems'],
        'Visualization': ['VIS', 'IEEE Transactions on Visualization and Computer Graphics']
    }
}
//Have to change everything to lowercase