export const areaDictionary = {
    'Emery Computer Science': {
        "vision": ['cvpr', 'iccv', 'eccv'],
        "plan": ['popl', 'pldi', 'oopsla', 'icfp'],
        "soft": ['icse', 'fse', 'ase', 'issta'],
        "ops": ['sosp', 'osdi', 'eurosys', 'fast', 'usenixatc'],
        'metrics': ['imc', 'sigmetrics'],
        'mobile': ['mobisys', 'mobicom', 'sensys'],
        'hpc': ['sc', 'hpdc', 'ics'],
        'bed': ['emsoft', 'rtss', 'rtas'],
        'da': ['iccad', 'dac'],
        'mod': ['vldb', 'sigmod', 'icde', 'pods'],
        'sec': ['ccs', 'oakland', 'usenixsec', 'ndss', 'ieee s&p', 'pets'],
        'comm': ['sigcomm', 'nsdi'],
        'arch': ['asplos', 'isca', 'micro', 'hpca', 'neurlps'],
        'log': ['cav', 'lics'],
        'act': ['focs', 'stoc', 'soda'],
        'mlmining': ['nips', 'icml', 'kdd'],
        'compgraph': ['siggraph', 'siggraph-asia'],
        'ir': ['sigir', 'www'],
        'chi': ['chiconf', 'ubicomp', 'uist', 'imwut, pervasive'],
        'nlp': ['emnlp', 'acl', 'naacl'],
        'robotics': ['icra', 'iros', 'rss'],
        'crypt': ['crypto', 'eurocrypt'],
        'bio': ['ismb', 'recomb'],
        'visual': ['vis', 'vr'],
        'ecom': ['ec', 'wine', 'cse'],
        'ai': ['aaai', 'ijcai']

    },
    'Computer Science': {
        'Artificial Intelligence': ['aaai', 'ijcai'],
        'Computer Vision': ['cvpr', 'eccv', 'iccv'],
        'Machine Learning & Data Mining': ['icml', 'kdd', 'neurips'],
        'Natural Language Processing': ['acl', 'emnlp', 'naacl'],
        'The Web and Information': ['sigir', 'www'],
        'Computer Architecture': ['asplos', 'isca', 'micro', 'hpca'],
        'Computer Networks': ['sigcomm', 'nsdi'],
        'Computer Security': ['ccs', 's&p', 'usenix', 'ndss'],
        'Databases': ['sigmod', 'vldb', 'icde', 'pods'],
        'Design Automation': ['dac', 'iccad'],
        'Embedded and Real-Time Systems': ['emsoft', 'rtas', 'rtss'],
        'High Performance Computing': ['hpdc', 'ics'],
        'Mobile Computing': ['mobicom', 'mobisys', 'sensys'],
        'Measurement and Performance Analysis': ['imc', 'sigmetrics'],
        'Operating Systems': ['osdi', 'sosp', 'eurosys'],
        'Programming Languages': ['pldi', 'popl', 'icfp', 'oopsla'],
        'Software Engineering': ['fse', 'icse', 'issta'],
        'Algorithms & Complexity': ['focs', 'soda', 'stoc', 'crypto', 'eurocrypt'],
        'Logic and Verification': ['cav', 'lics'],
        'Comp. bio & bioinformatics': ['ismb', 'recomb'],
        'Computer Graphics': ['siggraph', 'siggraph asia'],
        'Human-Computer Interaction': ['chi', 'ubicomp', 'uist'],
        'Robotics': ['icra', 'iros', 'rss'],
        'Visualization': ['vis']
    },
    'Physics': {
        'Astronomy and Astrophysics': ['websci', 'cidu', 'ims', 'irmmw-thz', 'eqec', 'ursi gass', 'nss', 'icpr', 'cpa', 'phystat', 'qels', 'icops', 'cleo', 'aeroconf', 'sfc', 'nss/mic', 'jicimwicte', 'siggraph', 'e-science', 'rta'],
        'Atomic and Molecular Physics': ['cleo', 'icsd', 'sispad', 'ectc', 'vlsit', 'eqec', 'qels', 'jcis', 'acoft', 'fts', 'pcm', 'icops', 'icmens', 'mines', 'cp', 'cpem', 'ivnc', 'mems', 'iemt'],
        'Condensed Matter Physics': ['intermag', 'cefc', 'cleo', 'apmrc', 'sispad', 'elt', 'iedm', 'ict', 'iwce', 'eqec', 'irmmw-thz', 'qels', 'iqec', 'drc', 'ifm', 'iprm', 'ieee-nano', 'sigetdm', 'ieeeaps', 'isaf'],
        'Nuclear and High Energy Physics': ['dis', 'icpa', 'icops', 'iwce', 'nss/mic'],
        'Surfaces and Interfaces': ['websci', 'nime', 'ius', 'iedm', 'ise', 'icoac', 'ssict', 'mse', 'pvsc', 'intermag', 'asdam', 'inec', 'hsi', 'jcis', 'iqec', 'leos', 'ipmm'],
        'Optics': ['cleo', 'ofc', 'ecoc', 'ius', 'eucap', 'isap', 'ieeeaps', 'nss/mic', 'eumc', 'ims', 'nss', 'irmmw-thz', 'qels', 'apmc', 'ivec', 'ipc', 'eqec', 'leos', 'icton', 'fcs']
    },

    'Mathematics': {
        'Algebra and Number Theory': ['Journal of Differential Geometry','Compositio Mathematica','Forum of Mathematics, Pi'],
        'Analysis': ["Annales de l'Institut Henri Poincaré C, Analyse non linéaire", "Geometric and Functional Analysis", "Archive for Rational Mechanics and Analysis"],
        'Applied Mathematics':['Journal of the American Mathematical Society',"IEEE Transactions on Pattern Analysis and Machine Intelligence", "Communications on Pure and Applied Mathematics"],
        'Computational Mathematics':["Journal of Computational Physics","Journal of Computational Chemistry"],
        'Geometry and Topology': ["Geometry & Topology","Geometric and Functional Analysis", "Journal of Topology"],
        'Numerical Analysis': ["Acta Numerica","R Journal","Analysis & PDE"],
        'Statistics and Probability': ["Journal of Statistical Software", "Journal of Machine Learning Research","Journal of the American Statistical Association", "Annals of Mathematics", "Annals of Statistics", "Annals of Probability"],
        'Discrete Mathematics and Combinatorics': ["Combinatorica","Journal of Combinatorial Theory, Series B","Journal of Combinatorial Theory, Series A","IEEE Transactions on Information Theory"]
    }
}
//Have to change everything to lowercase